### ISSUE TITLE
bpm

### ISSUE THREAD

**Issue by AmazingGame** [changeofpace/VivienneVMM#1]
Can this achieve unlimited hardware breakpoints?...

**Comment by changeofpace** [comment]
No, the project can only support four concurrent breakpoints at any given time.

You can achieve similar behavior without this restriction using EPT hooking. This project does not currently support this feature, but I intend to implement stealthy user mode EPT hooks in the future.

**Comment by changeofpace** [comment]
The ept breakpoint manager added in the 1.0.0 release supports unlimited ept breakpoints. 2992cadcb1330e28540fb9bf31a7a35de69e3556
