### ISSUE TITLE
ObOpenObjectByPointer returns 0xC000000D

### ISSUE THREAD

**Issue by kClydeee** [changeofpace/VivienneVMM#12]
it's same with invalid pid and exist process..
What's wrong?
----Dbgview.exe--------------------------------------------------------------------------------------------
18:29:38.971 DBG #03 [00] 12776  8380 VivienneCL.exe     Processing IOCTL_SET_EPT_BREAKPOINT.
18:29:38.971 ERR #03 [00] 12776  8380 VivienneCL.exe     ObOpenObjectByPointer failed: 0xC000000D
18:29:38.971 ERR #03 [00] 12776  8380 VivienneCL.exe     EbmpCreateLogContext failed: 0xC000000D
18:29:38.971 ERR #03 [00] 12776  8380 VivienneCL.exe     EbmSetEptBreakpoint failed: 0xC000000D

**Comment by BlackLuny** [comment]
I have the same problem in win10,It's just mapping the address to user space,you can do it by using mdl etc.

**Comment by changeofpace** [comment]
I pushed a fix in 5dce1e6. Let me know if it works.
