### ISSUE TITLE
Are there any plans to interrupt int1

### ISSUE THREAD

**Issue by wrenchonline** [changeofpace/VivienneVMM#9]
### For example,Update the tf flag

> pushfd
> or dword ptr [esp],100h 
> popfd  

Is there a better model?

**Comment by changeofpace** [comment]
The first interrupt vector gets hooked in the old hardware breakpoint manager so I'm not sure what you mean. Is the code you posted not handled correctly?

**Comment by wrenchonline** [comment]
I looked at the debugger code for the VBox，It uses int3 breakpoint manager.What are the drawbacks of this to be found?

**Comment by wrenchonline** [comment]
I'm not sure what the advantage of an EPT breakpoint is
